server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "vinradio"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.0"
    repository: "https://maven.lavalink.dev/releases"